#name: Check Dependencies
#
#on:
#  schedule:
#    - cron:  '0 0 * * *' # This will run the workflow every day at midnight
#
#jobs:
#  check:
#    runs-on: ubuntu-20.04
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#
#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#
#    - name: Maven Dependency Tree Dependency Submission
#      uses: advanced-security/maven-dependency-submission-action@v3.0.2

# Dependabot needs the maven dependencies sent to it using this Github action
# so that dependabot can interpret them or something.
name: Submit Dependency Snapshot
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
      with:
        token: ${{ secrets.MAVEN_DEPENDENCY_GH_ACTIONS_ACCESS_TOKEN }}
